package com.example.framework.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.framework.bean.MessageBean;
import com.example.framework.bean.ResultBean;
import com.example.framework.bean.ShopStepTimeRealBean;
import com.example.framework.greendao.FirstStepBean;
import com.example.framework.bean.AddressBarBean;

import com.example.framework.greendao.MessageBeanDao;
import com.example.framework.greendao.ResultBeanDao;
import com.example.framework.greendao.ShopStepTimeRealBeanDao;
import com.example.framework.greendao.FirstStepBeanDao;
import com.example.framework.greendao.AddressBarBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageBeanDaoConfig;
    private final DaoConfig resultBeanDaoConfig;
    private final DaoConfig shopStepTimeRealBeanDaoConfig;
    private final DaoConfig firstStepBeanDaoConfig;
    private final DaoConfig addressBarBeanDaoConfig;

    private final MessageBeanDao messageBeanDao;
    private final ResultBeanDao resultBeanDao;
    private final ShopStepTimeRealBeanDao shopStepTimeRealBeanDao;
    private final FirstStepBeanDao firstStepBeanDao;
    private final AddressBarBeanDao addressBarBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageBeanDaoConfig = daoConfigMap.get(MessageBeanDao.class).clone();
        messageBeanDaoConfig.initIdentityScope(type);

        resultBeanDaoConfig = daoConfigMap.get(ResultBeanDao.class).clone();
        resultBeanDaoConfig.initIdentityScope(type);

        shopStepTimeRealBeanDaoConfig = daoConfigMap.get(ShopStepTimeRealBeanDao.class).clone();
        shopStepTimeRealBeanDaoConfig.initIdentityScope(type);

        firstStepBeanDaoConfig = daoConfigMap.get(FirstStepBeanDao.class).clone();
        firstStepBeanDaoConfig.initIdentityScope(type);

        addressBarBeanDaoConfig = daoConfigMap.get(AddressBarBeanDao.class).clone();
        addressBarBeanDaoConfig.initIdentityScope(type);

        messageBeanDao = new MessageBeanDao(messageBeanDaoConfig, this);
        resultBeanDao = new ResultBeanDao(resultBeanDaoConfig, this);
        shopStepTimeRealBeanDao = new ShopStepTimeRealBeanDao(shopStepTimeRealBeanDaoConfig, this);
        firstStepBeanDao = new FirstStepBeanDao(firstStepBeanDaoConfig, this);
        addressBarBeanDao = new AddressBarBeanDao(addressBarBeanDaoConfig, this);

        registerDao(MessageBean.class, messageBeanDao);
        registerDao(ResultBean.class, resultBeanDao);
        registerDao(ShopStepTimeRealBean.class, shopStepTimeRealBeanDao);
        registerDao(FirstStepBean.class, firstStepBeanDao);
        registerDao(AddressBarBean.class, addressBarBeanDao);
    }
    
    public void clear() {
        messageBeanDaoConfig.clearIdentityScope();
        resultBeanDaoConfig.clearIdentityScope();
        shopStepTimeRealBeanDaoConfig.clearIdentityScope();
        firstStepBeanDaoConfig.clearIdentityScope();
        addressBarBeanDaoConfig.clearIdentityScope();
    }

    public MessageBeanDao getMessageBeanDao() {
        return messageBeanDao;
    }

    public ResultBeanDao getResultBeanDao() {
        return resultBeanDao;
    }

    public ShopStepTimeRealBeanDao getShopStepTimeRealBeanDao() {
        return shopStepTimeRealBeanDao;
    }

    public FirstStepBeanDao getFirstStepBeanDao() {
        return firstStepBeanDao;
    }

    public AddressBarBeanDao getAddressBarBeanDao() {
        return addressBarBeanDao;
    }

}
