package com.example.framework.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.framework.bean.UserBean;
import com.example.framework.bean.ShopStepTimeRealBean;

import com.example.framework.greendao.UserBeanDao;
import com.example.framework.greendao.ShopStepTimeRealBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig shopStepTimeRealBeanDaoConfig;

    private final UserBeanDao userBeanDao;
    private final ShopStepTimeRealBeanDao shopStepTimeRealBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        shopStepTimeRealBeanDaoConfig = daoConfigMap.get(ShopStepTimeRealBeanDao.class).clone();
        shopStepTimeRealBeanDaoConfig.initIdentityScope(type);

        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        shopStepTimeRealBeanDao = new ShopStepTimeRealBeanDao(shopStepTimeRealBeanDaoConfig, this);

        registerDao(UserBean.class, userBeanDao);
        registerDao(ShopStepTimeRealBean.class, shopStepTimeRealBeanDao);
    }
    
    public void clear() {
        userBeanDaoConfig.clearIdentityScope();
        shopStepTimeRealBeanDaoConfig.clearIdentityScope();
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public ShopStepTimeRealBeanDao getShopStepTimeRealBeanDao() {
        return shopStepTimeRealBeanDao;
    }

}
