package com.example.framework.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.framework.bean.ShopStepTimeRealBean;
import com.example.framework.bean.UserBean;
import com.example.framework.greendao.FirstStepBean;

import com.example.framework.greendao.ShopStepTimeRealBeanDao;
import com.example.framework.greendao.UserBeanDao;
import com.example.framework.greendao.FirstStepBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopStepTimeRealBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig firstStepBeanDaoConfig;

    private final ShopStepTimeRealBeanDao shopStepTimeRealBeanDao;
    private final UserBeanDao userBeanDao;
    private final FirstStepBeanDao firstStepBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopStepTimeRealBeanDaoConfig = daoConfigMap.get(ShopStepTimeRealBeanDao.class).clone();
        shopStepTimeRealBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        firstStepBeanDaoConfig = daoConfigMap.get(FirstStepBeanDao.class).clone();
        firstStepBeanDaoConfig.initIdentityScope(type);

        shopStepTimeRealBeanDao = new ShopStepTimeRealBeanDao(shopStepTimeRealBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        firstStepBeanDao = new FirstStepBeanDao(firstStepBeanDaoConfig, this);

        registerDao(ShopStepTimeRealBean.class, shopStepTimeRealBeanDao);
        registerDao(UserBean.class, userBeanDao);
        registerDao(FirstStepBean.class, firstStepBeanDao);
    }
    
    public void clear() {
        shopStepTimeRealBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
        firstStepBeanDaoConfig.clearIdentityScope();
    }

    public ShopStepTimeRealBeanDao getShopStepTimeRealBeanDao() {
        return shopStepTimeRealBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public FirstStepBeanDao getFirstStepBeanDao() {
        return firstStepBeanDao;
    }

}
