package com.example.point;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.point.service.StepBean;

import com.example.point.StepBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stepBeanDaoConfig;

    private final StepBeanDao stepBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stepBeanDaoConfig = daoConfigMap.get(StepBeanDao.class).clone();
        stepBeanDaoConfig.initIdentityScope(type);

        stepBeanDao = new StepBeanDao(stepBeanDaoConfig, this);

        registerDao(StepBean.class, stepBeanDao);
    }
    
    public void clear() {
        stepBeanDaoConfig.clearIdentityScope();
    }

    public StepBeanDao getStepBeanDao() {
        return stepBeanDao;
    }

}
