package com.example.framework;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.framework.bean.PointBean;
import com.example.framework.bean.StepBean;
import com.example.framework.bean.MessageBean;

import com.example.framework.PointBeanDao;
import com.example.framework.StepBeanDao;
import com.example.framework.MessageBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pointBeanDaoConfig;
    private final DaoConfig stepBeanDaoConfig;
    private final DaoConfig messageBeanDaoConfig;

    private final PointBeanDao pointBeanDao;
    private final StepBeanDao stepBeanDao;
    private final MessageBeanDao messageBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pointBeanDaoConfig = daoConfigMap.get(PointBeanDao.class).clone();
        pointBeanDaoConfig.initIdentityScope(type);

        stepBeanDaoConfig = daoConfigMap.get(StepBeanDao.class).clone();
        stepBeanDaoConfig.initIdentityScope(type);

        messageBeanDaoConfig = daoConfigMap.get(MessageBeanDao.class).clone();
        messageBeanDaoConfig.initIdentityScope(type);

        pointBeanDao = new PointBeanDao(pointBeanDaoConfig, this);
        stepBeanDao = new StepBeanDao(stepBeanDaoConfig, this);
        messageBeanDao = new MessageBeanDao(messageBeanDaoConfig, this);

        registerDao(PointBean.class, pointBeanDao);
        registerDao(StepBean.class, stepBeanDao);
        registerDao(MessageBean.class, messageBeanDao);
    }
    
    public void clear() {
        pointBeanDaoConfig.clearIdentityScope();
        stepBeanDaoConfig.clearIdentityScope();
        messageBeanDaoConfig.clearIdentityScope();
    }

    public PointBeanDao getPointBeanDao() {
        return pointBeanDao;
    }

    public StepBeanDao getStepBeanDao() {
        return stepBeanDao;
    }

    public MessageBeanDao getMessageBeanDao() {
        return messageBeanDao;
    }

}
