package com.example.framework;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.framework.bean.MinutesBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MINUTES_BEAN".
*/
public class MinutesBeanDao extends AbstractDao<MinutesBean, Long> {

    public static final String TABLENAME = "MINUTES_BEAN";

    /**
     * Properties of entity MinutesBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User = new Property(1, String.class, "user", false, "USER");
        public final static Property Minutes = new Property(2, String.class, "minutes", false, "MINUTES");
        public final static Property Step = new Property(3, int.class, "step", false, "STEP");
    }


    public MinutesBeanDao(DaoConfig config) {
        super(config);
    }
    
    public MinutesBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MINUTES_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER\" TEXT NOT NULL ," + // 1: user
                "\"MINUTES\" TEXT NOT NULL ," + // 2: minutes
                "\"STEP\" INTEGER NOT NULL );"); // 3: step
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MINUTES_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MinutesBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUser());
        stmt.bindString(3, entity.getMinutes());
        stmt.bindLong(4, entity.getStep());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MinutesBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUser());
        stmt.bindString(3, entity.getMinutes());
        stmt.bindLong(4, entity.getStep());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MinutesBean readEntity(Cursor cursor, int offset) {
        MinutesBean entity = new MinutesBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // user
            cursor.getString(offset + 2), // minutes
            cursor.getInt(offset + 3) // step
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MinutesBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser(cursor.getString(offset + 1));
        entity.setMinutes(cursor.getString(offset + 2));
        entity.setStep(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MinutesBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MinutesBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MinutesBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
