package com.example.framework;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.framework.bean.PointBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "POINT_BEAN".
*/
public class PointBeanDao extends AbstractDao<PointBean, Long> {

    public static final String TABLENAME = "POINT_BEAN";

    /**
     * Properties of entity PointBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Curr_date = new Property(1, String.class, "curr_date", false, "CURR_DATE");
        public final static Property Buy_title = new Property(2, String.class, "buy_title", false, "BUY_TITLE");
        public final static Property Point = new Property(3, int.class, "point", false, "POINT");
    }


    public PointBeanDao(DaoConfig config) {
        super(config);
    }
    
    public PointBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"POINT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CURR_DATE\" TEXT NOT NULL ," + // 1: curr_date
                "\"BUY_TITLE\" TEXT NOT NULL ," + // 2: buy_title
                "\"POINT\" INTEGER NOT NULL );"); // 3: point
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"POINT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PointBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getCurr_date());
        stmt.bindString(3, entity.getBuy_title());
        stmt.bindLong(4, entity.getPoint());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PointBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getCurr_date());
        stmt.bindString(3, entity.getBuy_title());
        stmt.bindLong(4, entity.getPoint());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PointBean readEntity(Cursor cursor, int offset) {
        PointBean entity = new PointBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // curr_date
            cursor.getString(offset + 2), // buy_title
            cursor.getInt(offset + 3) // point
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PointBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCurr_date(cursor.getString(offset + 1));
        entity.setBuy_title(cursor.getString(offset + 2));
        entity.setPoint(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PointBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PointBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PointBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
